export default {
  public: {
  },
  nav: {
    vision: 'Project vision',
    dfs: 'DFS token',
    project: 'Project progress',
    faq: 'FAQ',
  },
  index: {
    title1_1: 'An open blockchain financial network ',
    title1_2: 'that integrates a series of DeFi protocols ',
    btn_1: 'Try it ',
    title2_1: 'Let users from every corner of the world',
    title2_2: 'enjoy safe and equal financial services',
    cont2: 'Traditional financial infrastructures are isolated and fragmented from each other due to cultural differences and geographical restrictions governed by sovereignty. An open financial network based on blockchain technology will bring revolutionary changes to traditional financial infrastructure. This network can break down international financial barriers, collect global liquidity, create network effects, and create currency and financial programmability on a global scale.',
    link2: 'Read white paper',
    title3_1: 'DFS token',
    title3_2: 'Used for trading, community governance, liquidity incentives, dividends of protocol fees, staking, issuing and generating assets, etc.',
    cont3: 'By integrating a series of DeFi protocols, DeFis Network will form powerful network effect in blockchain finance field in the future. The platform coin DFS will continue to capture the value generated by these DeFi protocols. DFS holders will continue to receive dividends from protocol fees. Through smart contracts, dividends are automatically executed, so that each holder can share the dividends of DeFis Network development fairly.',
    status1: 'Listed',
    status2: 'Coming soon',
  }
}